export type Image = {
    id: number;
    itemId: number;
    image: string;
    position: number;
    created: Date | string | null;
    updated: Date | string | null;
}

export type MenuItem = {
    id: number;
    venueId: number | null;
    channelId: number | null;
    sourceId: number | null;
    menuId: number | null;
    sectionId: number | null;
    taxId: number | null;
    crossSellId: number | null;
    plu: string | null;
    externalId: string | null;
    name: string | null;
    internalName: string | null;
    description: string | null;
    additionalInfo: string | null;
    calories: string | null;
    deliveryFlag: number | null;
    pickupFlag: number | null;
    seatFlag: number | null;
    notesFlag: number | null;
    popularFlag: number | null;
    alcoholic: number | null;
    price: number;
    deliveryPriceOverride: number | null;
    seatPriceOverride: number | null;
    deliverooPriceOverride: number | null;
    deliveryHeroPriceOverride: number | null;
    glovoPriceOverride: number | null;
    justeatPriceOverride: number | null;
    uberPriceOverride: number | null;
    value: number | null;
    position: number | null;
    expiryDays: number | null;
    visible: number | null;
    availableDate: Date | string | null;
    availabilityType: string;
    quantity: number | null;
    factor: string | null;
    eventCap: string | null;
    sku: string | null;
    voucherType: string | null;
    assignCode: string | null;
    assignCodeType: string | null;
    hasMessage: boolean | null;
    leadTime: number | null;
    leadDays: number | null;
    leadDaysTime: number | null;
    mealDeal: number | null;
    external: number | null;
    url: string | null;
    gfcId: number | null;
    created: Date | string | null;
    updated: Date | string | null;
    isOfferItem: boolean | null;
    modifierIds: number[] | null;
    customTagIds: number[] | null;
    earnTagIds: number[] | null;
    awardTagIds: number[] | null;
    modifiers: string[] | null;
    offers: string[] | null;
    images: Image[] | null;
    tags: string[] | null;
    customTags: string[] | null;
    earnTags: string[] | null;
    awardTags: string[] | null;
    tagActions: string[] | null;
    gfcData: string | null;
    availableForPublish: boolean | null;
    comboMeals: string[] | null;
    comboMealId: string | null;
    available: boolean | null;
}